name: Deploy Java Web App to Azure

on:
  [push,pull_request]

env:
  JAVA_VERSION: '1.8'                # set this to the node version to use
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io   # set this to Container Registry name 
  AZURE_RESOURCE_GROUP: ActionsDemo   # set this to your Azure Resource group's name 
  AZURE_APP_PLAN: ActionPlan  # set this to your App service plan's name 
 
jobs: 
  build:
#     needs: provision-webapp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Build with Maven
      run: |
        mvn clean install --file pom.xml -Dmaven.test.skip=true
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
        azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_PROJECT_URL }}
        # Name of the Azure Pipline to be triggered
        azure-pipeline-name: 'MyFirstProject-Maven-CI'
        # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
