name: Deploy Java Web App to Azure

on:
  [push,pull_request] 
 
jobs: 
  build:
#     needs: provision-webapp
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
        azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_PROJECT_URL }}
        # Name of the Azure Pipline to be triggered
        azure-pipeline-name: 'chadcrowell-code.collj2l3'
        # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
